### ISSUE TITLE
pyOCD no sudo warnings in Ubuntu

### ISSUE THREAD

**Issue by korjaa** [mbedmicro/pyOCD#267]
pyOCD 0.8.0 doesn't give any warnings if sudo or udev rule is missing, it just reports "No available boards are connected".

I'm using Ubuntu 16.04.1 with Virtualbox on Windows 7.

**Comment by flit** [comment]
Closing this issue. The readme has been updated with information about udev rules, and an example udev rule file is included (`udev/50-pyocd.rules`).

Also, pyOCD will now output a debug log message if it gets an exception trying to read a USB device's product name, saying it might be a permissions issue. It has to be a debug log because pyOCD cannot tell if the device is one that you might *want* to access or something else (like a mouse or printer) because it cannot read the device's properties.
