### ISSUE TITLE
pyOCD does not support compare-sections

### ISSUE THREAD

**Issue by bremoran** [mbedmicro/pyOCD#89]
When new microcontrollers are added to pyOCD, particularly those with new flash algorithms, it's helpful to be able to verify the contents of the flash to be sure that the elf which was written actually appears, as intended, on the MCU.  Without this, issues such as #88 will continue to pop up every so often.

The standard workflow is Erase->Program->Verify->Run.  Without the verify step, there's no way to know what the MCU is actually running.

Support for the gdb compare-sections command is vital.

**Comment by 0xc0170** [comment]
I have looked at qCRC packet to add its support to pyOCD. I'll share some snippets of code, might help somebody to look at this enhancement:

```
       // added to handleQuery()
        elif query[0] == 'CRC':
            # CRC checksum of a block memory using crc-32
            data = query[1].split(',')
            resp = self.checksum_memory(int(data[0], 16), int(data[1].split('#')[0], 16))
            return self.createRSPPacket(resp)

    // new function
    def checksum_memory(self, address, size):
        words = self.target.readBlockMemoryAligned32(address, size)
        return 'C' + str(1)
```

The new function which should calculate CRC, just returns rensponse with crc-32 being 1, the reading seems to be really slow and problematic at the moment. Small sectors were ok, Mismatched but were at least read, but sectors like where is the code, were timeout and transfer layer returns TransferError() after gdb issued "Ignoring packet error"

**Comment by c1728p9** [comment]
I looked into implementing this from 0xC0170's changes, but it is working for me without any modifications.  I'm using GDB 7.8.1.  When the qCRC packet is missing, gdb falls back to using direct memory reads.  

It looks like the qCRC might just be an optimization: https://sourceware.org/gdb/onlinedocs/gdb/Memory.html
In pyOCD's case computing the CRC wouldn't speed things up much, since reading data from the target is the main bottle neck, not sending the data over a socket.

**Comment by c1728p9** [comment]
Can this issue be closed since GDB already has this feature?

**Comment by c1728p9** [comment]
Closing this issue.  Please re-open if you experience problems wehn running the compare-sections command from gdb.
